// importImages.js
import adfriends from './assets/imgs/add-friends.png';
import arrow from './assets/imgs/arrow.png';
import arrows from './assets/imgs/arrows.png';
import comments from './assets/imgs/comments.png';
import display from './assets/imgs/display.png';
import feedOne from './assets/imgs/feed-image-1.jpg';
import feedTwo from './assets/imgs/feed-image-2.jpg';
import feedback from './assets/imgs/feedback.png';
import feeling from './assets/imgs/feeling.png';
import friends from './assets/imgs/friends.png';
import group from './assets/imgs/group.png';
import help from './assets/imgs/help.png';
import inbox from './assets/imgs/inbox.png';
import likeBlue from './assets/imgs/like-blue.png';
import like from './assets/imgs/like.png';
import liveVideo from './assets/imgs/live-video.png';
import location from './assets/imgs/location.png'
import logo from './assets/imgs/logo.png';
import logoutimage from './assets/imgs/logout.png';
import more from './assets/imgs/more.png';
import photo from './assets/imgs/photo.png';
import photoTwo from './assets/imgs/photo2.png';
import profile from './assets/imgs/profile-pic.jpg';
import profileStudy from './assets/imgs/profile-study.png';
import searchImage from './assets/imgs/search.png';
import seeMore from './assets/imgs/see-more.png';
import setting from './assets/imgs/setting.png';
import share from './assets/imgs/share.png';
import shortcutOne from './assets/imgs/shortcut-1.png';
import shortcutTwo from './assets/imgs/shortcut-2.png';
import shortcutThree from './assets/imgs/shortcut-3.png';
import shortcutFour from './assets/imgs/shortcut-4.png';
import shortcutFive from './assets/imgs/shortcut-5.png';
import shortcutSix from './assets/imgs/shortcut-6.png';
import shortcutSeven from './assets/imgs/shortcut-7.png';
import shortcutEight from './assets/imgs/shortcut-8.png';
import tcWeek from './assets/imgs/TCWek.png'
import upload from './assets/imgs/upload.png'

export { adfriends, arrow, arrows, comments, display, feedOne, feedTwo, feedback, feeling, friends, group, help, inbox, likeBlue, like, liveVideo, location, logo, logoutimage, more, photo, photoTwo, profile, profileStudy, searchImage, seeMore, setting, share, shortcutOne, shortcutTwo, shortcutThree, shortcutFour, shortcutFive, shortcutSix, shortcutSeven, shortcutEight, tcWeek, upload };